### PR TITLE
Docker Support

### PR DESCRIPTION
**Pull request by victorkifer**
Nowadays Docker is a widely adopted technology. And also VirtualBox support is currently limited.

This merge request provides the support for Docker via `docker-compose`.

### CODE REVIEW

**Comment by Li357** [comment]
+1 I tried installing via Vagrant and Ansible but couldn't get far. Using docker was an error-free process.

**Comment by michaelpginn** [comment]
Trying to setup, anyone else getting "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vDiX1T/psycopg2/"?

**Comment by victorkifer** [comment]
@milesper probably related to https://github.com/psycopg/psycopg2/issues/560. I will try to add fix in 2-3 days.

**Comment by j0nscalet** [comment]
This works, really well. Thanks @victorkifer! @taylorhughes mind merging this?

**Comment by victorkifer** [comment]
Closing this one in favour of https://github.com/LaunchKit/LaunchKit/pull/48. I changed the branch, but the changes are the same.

**Pull request closed without merging**
